import pandas as pd

# Extended dictionary with additional database systems
data_types = [
    {
        "sql_type": "bit",
        "sql_category": "boolean",
        "min_value": False,
        "max_value": True,
        "pandas_type": "boolean",
    },
    {
        "sql_type": "tinyint",
        "sql_category": "exact_whole_numeric",
        "min_value": 0,
        "max_value": 255,
        "pandas_type": "UInt8",
    },
    {
        "sql_type": "smallint",
        "sql_category": "exact_whole_numeric",
        "min_value": -(2**15),
        "max_value": 2**15 - 1,
        "pandas_type": "Int16",
    },
    {
        "sql_type": "int",
        "sql_category": "exact_whole_numeric",
        "min_value": -(2**31),
        "max_value": 2**31 - 1,
        "pandas_type": "Int32",
    },
    {
        "sql_type": "integer",
        "sql_category": "exact_whole_numeric",
        "min_value": -(2**31),
        "max_value": 2**31 - 1,
        "pandas_type": "Int32",
    },
    {
        "sql_type": "bigint",
        "sql_category": "exact_whole_numeric",
        "min_value": -(2**63),
        "max_value": 2**63 - 1,
        "pandas_type": "Int64",
    },
    {
        "sql_type": "float",
        "sql_category": "approximate_decimal_numeric",
        "min_value": -(1.79**308),
        "max_value": 1.79**308,
        "pandas_type": "float64",
    },
    {
        "sql_type": "numeric",
        "sql_category": "exact_decimal_numeric",
        "min_value": -float('inf'),
        "max_value": float('inf'),
        "pandas_type": "object",
    },
    {
        "sql_type": "decimal",
        "sql_category": "exact_decimal_numeric",
        "min_value": -float('inf'),
        "max_value": float('inf'),
        "pandas_type": "object",
    },
    {
        "sql_type": "date",
        "sql_category": "date_time",
        "min_value": pd.Timestamp((pd.Timestamp.min + pd.Timedelta(days=1)).date()),
        "max_value": pd.Timestamp(pd.Timestamp.max.date()),
        "pandas_type": "datetime64[ns]",
    },
    {
        "sql_type": "datetime",
        "sql_category": "date_time",
        "min_value": pd.Timestamp(1753, 1, 1, 0, 0, 0),
        "max_value": pd.Timestamp(1900, 1, 1) + pd.Timedelta.max,
        "pandas_type": "datetime64[ns]",
    },
    {
        "sql_type": "char",
        "sql_category": "character string",
        "min_value": 1,
        "max_value": 0,
        "pandas_type": "string",
    },
    {
        "sql_type": "varchar",
        "sql_category": "character string",
        "min_value": 1,
        "max_value": 0,
        "pandas_type": "string",
    },
    {
        "sql_type": "text",
        "sql_category": "character string",
        "min_value": 1,
        "max_value": 0,
        "pandas_type": "string",
    },
    {
        "sql_type": "binary",
        "sql_category": "binary",
        "min_value": -float('inf'),
        "max_value": float('inf'),
        "pandas_type": "object",
    },
    {
        "sql_type": "varbinary",
        "sql_category": "binary",
        "min_value": -float('inf'),
        "max_value": float('inf'),
        "pandas_type": "object",
    },
    {
        "sql_type": "json",
        "sql_category": "json",
        "pandas_type": "object",
    },
    {
        "sql_type": "jsonb",
        "sql_category": "json",
        "pandas_type": "object",
    },
    {
        "sql_type": "uuid",
        "sql_category": "uuid",
        "pandas_type": "object",
    },
    {
        "sql_type": "timestamp",
        "sql_category": "date_time",
        "min_value": pd.Timestamp.min,
        "max_value": pd.Timestamp.max,
        "pandas_type": "datetime64[ns]",
    },
    {
        "sql_type": "timestamptz",
        "sql_category": "date_time",
        "min_value": pd.Timestamp.min,
        "max_value": pd.Timestamp.max,
        "pandas_type": "datetime64[ns]",
    },
    # Add more mappings as needed
]
